title: Kim's Site
description: My first site
show_downloads: true
theme: jekyll-theme-cayman
url: kgurwitz.github.io

# Social Media

twitter_username: kgurwitz
github_username:  kgurwitz

# Build settings
markdown: kramdown

# Google Services

google_analytics:
